#!/bin/sh /etc/rc.common

START=99
APP=fastdick
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start()
{
	enabled=`uci get fastdick.setting.enabled 2>/dev/null`
	if [ "$enabled" -ne 1 ]
		then
		rm -rf /var/state/fastdick
		exit
	fi
	service_start /usr/bin/fastdick
}

stop()
{
	pid=`uci -P /var/state get fastdick.pid 2>/dev/null`
	if [ `echo -n "$pid" | wc -c` -ne 0 ]
		then
		if [ "$pid" -gt 0 ]
		then
			kill "$pid"
			cd /proc
			for cpid in [0-9]*
			do
			        if grep "PPid:	$pid" $cpid/status &>/dev/null
			        then
			                echo $cpid
			                name=`cat $cpid/status | grep "Name:" | sed 's/Name://' | tr -d ' \n\t'`
			                if [ "$name" = "sleep" ]
			                then
			                        kill $cpid
			                fi
			        fi
			done			
		fi
	fi
	rm -rf /var/state/fastdick

}

restart()
{
	stop
	start
}
